name: Build and push Docker image
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: tabletop-game
          image-tag: latest
