name: Build and deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: tabletop-game
          image-tag: latest
  deploy-githib-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Copy files intended for the destination repo
        run: |
          mkdir _site
          cp -R dist _site
          cp index.html _site
          cp -R texture _site
          cp icon.png _site
          mkdir _site/.github
          cp -R .github/_workflows _site/.github
      - name: Deploy website
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: _site/
          destination-github-username: TimurTripp-com
          destination-repository-name: tabletop-game-timurtripp-com.github.io
          target-branch: main
